### ISSUE TITLE
request: Patch pretty-show-1.6.16

### ISSUE THREAD

**Issue by phanimahesh** [typelead/eta-hackage#72]
It imports Paths_pretty_show module which is unsafe, and build fails.

There's just one exported function that uses it, should it be removed, along with the module dependency? [Something like this?](https://github.com/phanimahesh/pretty-show/commit/d722ea0f3ee8c26847d46edf271b0c145dffd89b)

`Paths_...` modules seem to be special, autogenerated to have a few functions returning hard-coded paths. I'm still not sure what they are useful for, but can they be supported in eta?

**Comment by Jyothsnasrinivas** [comment]
@phanimahesh Thanks for reporting and apologies for the late response! We recently patched the pretty-show package and it is on commit 04d711a661d86f9c33ec3512126bfd7a8a105ce8. This packages works only with the recent Eta, since we had to fix a compiler bug in order for it to work. 

Let me know if you face anymore problems.
